-- Parcours du catalogue

-- 1.
-- Connection du client
SELECT ADRESSEMAIL, MDPUTILISATEUR
FROM Client
Where ADRESSEMAIL = 'jp_polnareff@bucciarati.com';

-- 2.
-- Parcours des catégories
SELECT DISTINCT c.CATEGORIEMERE
FROM CATEGORIE c
ORDER BY c.CATEGORIEMERE ASC;

-- Parcours des sous-catégories
SELECT c.NOMCATEGORIE
FROM CATEGORIE c
WHERE c.NOMCATEGORIE <> c.CATEGORIEMERE
ORDER BY c.NOMCATEGORIE ASC;

-- Recommandation générale
SELECT cato
FROM(
SELECT AVG(compt), cato
FROM(

SELECT PRODUIT.IDPRODUIT, PRODUIT.NOMCATEGORIE as cato, COUNT(OFFRE.IDPRODUIT) as compt, PRODUIT.INTITULE as inti
FROM  OFFRE, PRODUIT, CATEGORIE
WHERE OFFRE.IDPRODUIT (+)= PRODUIT.IDPRODUIT
AND PRODUIT.NOMCATEGORIE = CATEGORIE.NOMCATEGORIE
GROUP BY PRODUIT.IDPRODUIT, PRODUIT.NOMCATEGORIE, PRODUIT.INTITULE

)
GROUP BY cato
ORDER BY AVG(compt) DESC, cato ASC);

-- Recommandation par utilisateur (ici pour l'utilisateur 2)
SELECT PRODUIT.NOMCATEGORIE as cato, COUNT(OFFRE.IDPRODUIT) as compt
FROM  OFFRE, PRODUIT, CATEGORIE
WHERE OFFRE.IDPRODUIT (+)= PRODUIT.IDPRODUIT
AND PRODUIT.NOMCATEGORIE = CATEGORIE.NOMCATEGORIE
AND OFFRE.IDUTILISATEUR = 2
AND PRODUIT.IDPRODUIT in (

SELECT p.IDPRODUIT
FROM PRODUIT p, OFFRE o
MINUS
SELECT distinct p.IDPRODUIT
FROM PRODUIT p, OFFRE o
WHERE o.ACHATREUSSI = 1
AND p.IDPRODUIT = o.IDPRODUIT
AND o.IDUTILISATEUR = 2

)
GROUP BY PRODUIT.NOMCATEGORIE
ORDER BY compt DESC, cato ASC;

-- 3.Consultation de la fiche complète des produits sélectionnés
SELECT INTITULE, DESCRIPT, NOMCATEGORIE, URLIMAGE, IDPRODUIT, PRIXCOURANT
FROM PRODUIT
WHERE IDPRODUIT = 7;

SELECT NOMCARACTERISTIQUE, VALEURCARACTERISTIQUE
FROM CARACTERISTIQUE
WHERE IDPRODUIT = 7;